#!/usr/bin/env python

import argparse
import logging

import matplotlib.pyplot as plt
import rosbag_pandas


def build_parser():
    """
    Builds the parser for reading the command line arguments
    :return: Argument parser
    """
    parser = argparse.ArgumentParser(description='Bagfile key to graph')
    parser.add_argument('-b', '--bag', help='Bag file to read',
                        required=True, type=str)
    parser.add_argument('-k', '--key',
                        help='Key you would like to plot',
                        required=True, nargs='*')
    parser.add_argument('-y ', '--ylim',
                        help='Set min and max y lim',
                        required=False, nargs=2)
    parser.add_argument('-c', '--combined',
                        help="Graph them all on one",
                        required=False, action="store_true", dest="sharey")
    parser.add_argument('-v', '--verbose',
                        help="Log verbose",
                        default=False, action="store_true")
    parser.add_argument('-o', '--offset',
                        help="offsets for each topic",
                        default=None)
    parser.add_argument('-l', '--labels',
                        help='Labels to use instead of topic names, topic names otherwise',
                        default = None, nargs='*')
    return parser


def graph(df, keys, sharey, offsets, labels):

    if offsets is not None:
        offsets = [float(off) for off in offsets.split(',')]
    else:
        offsets = [0]*len(keys)

    if labels is None:
        labels = keys

    if sharey or len(keys) == 1:
        fig, axes = plt.subplots(figsize=(10,6))
        fig.figsize=(10,5)
        for key, offset, label in zip(keys,offsets, labels):
            s = df[key].dropna() - offset
            #s = df[key].fillna(method="bfill") - offset
            axes.plot(s.index, s.values, label=label)

        axes.legend(loc=0)
        plt.show()
    else:
        fig, axes = plt.subplots(len(keys), sharex=True)
        idx = 0
        for key, offset, label in zip(keys,offsets, labels):
            s = df[key].dropna() - offset
            #s = df[key].fillna(value = 0.0) - offset
            axes[idx].plot(s.index, s.values)
            axes[idx].set_title(label)
            idx = idx + 1
        plt.show()


if __name__ == '__main__':
    parser = build_parser()
    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    topics = rosbag_pandas.topics_from_keys(args.key)
    df = rosbag_pandas.bag_to_dataframe(args.bag, include=topics)
    graph(df, args.key, args.sharey, args.offset, args.labels)
